// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'polling_unit.g.dart';

@JsonSerializable(
  fieldRename: FieldRename.snake,
)
class PollingUnit {
  String? gender;
  String? vin;
  String? firstName;
  String? lastName;
  String? pollingUnit;
  String? dateOfBirth;

  PollingUnit({
    this.gender,
    this.vin,
    this.firstName,
    this.lastName,
    this.pollingUnit,
    this.dateOfBirth,
  });

  factory PollingUnit.fromJson(Map<String, dynamic> json) =>
      _$PollingUnitFromJson(json);
}
